### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by devoncarew**
- add a link to the getting set up blog post

@danrubel @keertip

### CODE REVIEW

**Comment by devoncarew** [comment]
fix https://github.com/dart-lang/eclipse3/issues/2

**Comment by danrubel** [comment]
LGTM

**Comment by keertip** [comment]
Awesome!

**Comment by danrubel** [comment]
Change landed in https://github.com/dart-lang/eclipse3/commit/83c7439ec27238349b658e5bf7e8a2f3848324de
Should we cleanup this branch?

**Comment by devoncarew** [comment]
sure! closing...

**Pull request closed without merging**
